# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.models.weight_uo_m import WeightUoM  # noqa: E501
from psrestful.rest import ApiException


class TestWeightUoM(unittest.TestCase):
    """WeightUoM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWeightUoM(self):
        """Test WeightUoM"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.weight_uo_m.WeightUoM()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
