# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.models.tolerance_details import ToleranceDetails  # noqa: E501
from psrestful.rest import ApiException


class TestToleranceDetails(unittest.TestCase):
    """ToleranceDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testToleranceDetails(self):
        """Test ToleranceDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tolerance_details.ToleranceDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
