# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.models.order_status_details_response import OrderStatusDetailsResponse  # noqa: E501
from psrestful.rest import ApiException


class TestOrderStatusDetailsResponse(unittest.TestCase):
    """OrderStatusDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderStatusDetailsResponse(self):
        """Test OrderStatusDetailsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.order_status_details_response.OrderStatusDetailsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
