# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.api.purchase_order_api import PurchaseOrderApi  # noqa: E501
from psrestful.rest import ApiException


class TestPurchaseOrderApi(unittest.TestCase):
    """PurchaseOrderApi unit test stubs"""

    def setUp(self):
        self.api = PurchaseOrderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_supported_order_types(self):
        """Test case for get_supported_order_types

        Get Supported Order Types  # noqa: E501
        """
        pass

    def test_send_po(self):
        """Test case for send_po

        Send Po  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
