# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.api.product_price_and_configuration_api import ProductPriceAndConfigurationApi  # noqa: E501
from psrestful.rest import ApiException


class TestProductPriceAndConfigurationApi(unittest.TestCase):
    """ProductPriceAndConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = ProductPriceAndConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_available_charges(self):
        """Test case for get_available_charges

        Get Available Charges  # noqa: E501
        """
        pass

    def test_get_available_locations(self):
        """Test case for get_available_locations

        Get Available Locations  # noqa: E501
        """
        pass

    def test_get_configuration_and_pricing(self):
        """Test case for get_configuration_and_pricing

        Get Configuration And Pricing  # noqa: E501
        """
        pass

    def test_get_decoration_colors(self):
        """Test case for get_decoration_colors

        Get Decoration Colors  # noqa: E501
        """
        pass

    def test_get_fob_points(self):
        """Test case for get_fob_points

        Get Fob Points  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
