# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.models.account_info import AccountInfo  # noqa: E501
from psrestful.rest import ApiException


class TestAccountInfo(unittest.TestCase):
    """AccountInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountInfo(self):
        """Test AccountInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.account_info.AccountInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
