# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.api.default_api import DefaultApi  # noqa: E501
from psrestful.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_service_codes(self):
        """Test case for get_service_codes

        Get Service Codes  # noqa: E501
        """
        pass

    def test_get_services(self):
        """Test case for get_services

        Get Services  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
