# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.models.layers import Layers  # noqa: E501
from psrestful.rest import ApiException


class TestLayers(unittest.TestCase):
    """Layers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLayers(self):
        """Test Layers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.layers.Layers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
