# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.models.class_type import ClassType  # noqa: E501
from psrestful.rest import ApiException


class TestClassType(unittest.TestCase):
    """ClassType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClassType(self):
        """Test ClassType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.class_type.ClassType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
