# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.models.part_input import PartInput  # noqa: E501
from psrestful.rest import ApiException


class TestPartInput(unittest.TestCase):
    """PartInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartInput(self):
        """Test PartInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.part_input.PartInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
