# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.models.currency_supported_array import CurrencySupportedArray  # noqa: E501
from psrestful.rest import ApiException


class TestCurrencySupportedArray(unittest.TestCase):
    """CurrencySupportedArray unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurrencySupportedArray(self):
        """Test CurrencySupportedArray"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.currency_supported_array.CurrencySupportedArray()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
