# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.models.tolerance_type import ToleranceType  # noqa: E501
from psrestful.rest import ApiException


class TestToleranceType(unittest.TestCase):
    """ToleranceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testToleranceType(self):
        """Test ToleranceType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tolerance_type.ToleranceType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
