# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.models.part_array_input import PartArrayInput  # noqa: E501
from psrestful.rest import ApiException


class TestPartArrayInput(unittest.TestCase):
    """PartArrayInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartArrayInput(self):
        """Test PartArrayInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.part_array_input.PartArrayInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
