# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.models.fob_array import FobArray  # noqa: E501
from psrestful.rest import ApiException


class TestFobArray(unittest.TestCase):
    """FobArray unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFobArray(self):
        """Test FobArray"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.fob_array.FobArray()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
