# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.models.dimension_uo_m_output import DimensionUoMOutput  # noqa: E501
from psrestful.rest import ApiException


class TestDimensionUoMOutput(unittest.TestCase):
    """DimensionUoMOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDimensionUoMOutput(self):
        """Test DimensionUoMOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.dimension_uo_m_output.DimensionUoMOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
