# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.models.contact_details_input import ContactDetailsInput  # noqa: E501
from psrestful.rest import ApiException


class TestContactDetailsInput(unittest.TestCase):
    """ContactDetailsInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContactDetailsInput(self):
        """Test ContactDetailsInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.contact_details_input.ContactDetailsInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
