# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import psrestful
from psrestful.models.apparel_size import ApparelSize  # noqa: E501
from psrestful.rest import ApiException


class TestApparelSize(unittest.TestCase):
    """ApparelSize unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApparelSize(self):
        """Test ApparelSize"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.apparel_size.ApparelSize()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
