# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from psrestful.api_client import ApiClient


class InventoryApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_filter_values(self, supplier_code, api_version, product_id, **kwargs):  # noqa: E501
        """Get Filter Values  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_filter_values(supplier_code, api_version, product_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object supplier_code: (required)
        :param object api_version: (required)
        :param object product_id: (required)
        :param object body:
        :param object x_forwarded_for:
        :param object x_account_id:
        :param object product_id_type:
        :param object environment:
        :return: FilterValuesResponseV200
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_filter_values_with_http_info(supplier_code, api_version, product_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_filter_values_with_http_info(supplier_code, api_version, product_id, **kwargs)  # noqa: E501
            return data

    def get_filter_values_with_http_info(self, supplier_code, api_version, product_id, **kwargs):  # noqa: E501
        """Get Filter Values  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_filter_values_with_http_info(supplier_code, api_version, product_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object supplier_code: (required)
        :param object api_version: (required)
        :param object product_id: (required)
        :param object body:
        :param object x_forwarded_for:
        :param object x_account_id:
        :param object product_id_type:
        :param object environment:
        :return: FilterValuesResponseV200
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['supplier_code', 'api_version', 'product_id', 'body', 'x_forwarded_for', 'x_account_id', 'product_id_type', 'environment']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_filter_values" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'supplier_code' is set
        if ('supplier_code' not in params or
                params['supplier_code'] is None):
            raise ValueError("Missing the required parameter `supplier_code` when calling `get_filter_values`")  # noqa: E501
        # verify the required parameter 'api_version' is set
        if ('api_version' not in params or
                params['api_version'] is None):
            raise ValueError("Missing the required parameter `api_version` when calling `get_filter_values`")  # noqa: E501
        # verify the required parameter 'product_id' is set
        if ('product_id' not in params or
                params['product_id'] is None):
            raise ValueError("Missing the required parameter `product_id` when calling `get_filter_values`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'supplier_code' in params:
            path_params['supplier_code'] = params['supplier_code']  # noqa: E501
        if 'api_version' in params:
            path_params['api_version'] = params['api_version']  # noqa: E501
        if 'product_id' in params:
            path_params['product_id'] = params['product_id']  # noqa: E501

        query_params = []
        if 'product_id_type' in params:
            query_params.append(('product_id_type', params['product_id_type']))  # noqa: E501
        if 'environment' in params:
            query_params.append(('environment', params['environment']))  # noqa: E501

        header_params = {}
        if 'x_forwarded_for' in params:
            header_params['X-Forwarded-For'] = params['x_forwarded_for']  # noqa: E501
        if 'x_account_id' in params:
            header_params['x-account-id'] = params['x_account_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIKeyHeader', 'HTTPBasic', 'OAuth2PasswordBearer']  # noqa: E501

        return self.api_client.call_api(
            '/v{api_version}/suppliers/{supplier_code}/inventory/filter-values/{product_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FilterValuesResponseV200',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_inventory_by_product_v121(self, supplier_code, product_id, **kwargs):  # noqa: E501
        """Get Inventory By Product V121  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_inventory_by_product_v121(supplier_code, product_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object supplier_code: (required)
        :param object product_id: (required)
        :param object body:
        :param object x_forwarded_for:
        :param object x_account_id:
        :param object environment:
        :return: InventoryLevelsResponseV121
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_inventory_by_product_v121_with_http_info(supplier_code, product_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_inventory_by_product_v121_with_http_info(supplier_code, product_id, **kwargs)  # noqa: E501
            return data

    def get_inventory_by_product_v121_with_http_info(self, supplier_code, product_id, **kwargs):  # noqa: E501
        """Get Inventory By Product V121  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_inventory_by_product_v121_with_http_info(supplier_code, product_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object supplier_code: (required)
        :param object product_id: (required)
        :param object body:
        :param object x_forwarded_for:
        :param object x_account_id:
        :param object environment:
        :return: InventoryLevelsResponseV121
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['supplier_code', 'product_id', 'body', 'x_forwarded_for', 'x_account_id', 'environment']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_inventory_by_product_v121" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'supplier_code' is set
        if ('supplier_code' not in params or
                params['supplier_code'] is None):
            raise ValueError("Missing the required parameter `supplier_code` when calling `get_inventory_by_product_v121`")  # noqa: E501
        # verify the required parameter 'product_id' is set
        if ('product_id' not in params or
                params['product_id'] is None):
            raise ValueError("Missing the required parameter `product_id` when calling `get_inventory_by_product_v121`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'supplier_code' in params:
            path_params['supplier_code'] = params['supplier_code']  # noqa: E501
        if 'product_id' in params:
            path_params['product_id'] = params['product_id']  # noqa: E501

        query_params = []
        if 'environment' in params:
            query_params.append(('environment', params['environment']))  # noqa: E501

        header_params = {}
        if 'x_forwarded_for' in params:
            header_params['X-Forwarded-For'] = params['x_forwarded_for']  # noqa: E501
        if 'x_account_id' in params:
            header_params['x-account-id'] = params['x_account_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIKeyHeader', 'HTTPBasic', 'OAuth2PasswordBearer']  # noqa: E501

        return self.api_client.call_api(
            '/v1.2.1/suppliers/{supplier_code}/inventory/{product_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InventoryLevelsResponseV121',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_inventory_by_product_v200(self, supplier_code, product_id, **kwargs):  # noqa: E501
        """Get Inventory By Product V200  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_inventory_by_product_v200(supplier_code, product_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object supplier_code: (required)
        :param object product_id: (required)
        :param object body:
        :param object x_forwarded_for:
        :param object x_account_id:
        :param object environment:
        :return: InventoryLevelsResponseV200
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_inventory_by_product_v200_with_http_info(supplier_code, product_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_inventory_by_product_v200_with_http_info(supplier_code, product_id, **kwargs)  # noqa: E501
            return data

    def get_inventory_by_product_v200_with_http_info(self, supplier_code, product_id, **kwargs):  # noqa: E501
        """Get Inventory By Product V200  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_inventory_by_product_v200_with_http_info(supplier_code, product_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object supplier_code: (required)
        :param object product_id: (required)
        :param object body:
        :param object x_forwarded_for:
        :param object x_account_id:
        :param object environment:
        :return: InventoryLevelsResponseV200
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['supplier_code', 'product_id', 'body', 'x_forwarded_for', 'x_account_id', 'environment']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_inventory_by_product_v200" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'supplier_code' is set
        if ('supplier_code' not in params or
                params['supplier_code'] is None):
            raise ValueError("Missing the required parameter `supplier_code` when calling `get_inventory_by_product_v200`")  # noqa: E501
        # verify the required parameter 'product_id' is set
        if ('product_id' not in params or
                params['product_id'] is None):
            raise ValueError("Missing the required parameter `product_id` when calling `get_inventory_by_product_v200`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'supplier_code' in params:
            path_params['supplier_code'] = params['supplier_code']  # noqa: E501
        if 'product_id' in params:
            path_params['product_id'] = params['product_id']  # noqa: E501

        query_params = []
        if 'environment' in params:
            query_params.append(('environment', params['environment']))  # noqa: E501

        header_params = {}
        if 'x_forwarded_for' in params:
            header_params['X-Forwarded-For'] = params['x_forwarded_for']  # noqa: E501
        if 'x_account_id' in params:
            header_params['x-account-id'] = params['x_account_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIKeyHeader', 'HTTPBasic', 'OAuth2PasswordBearer']  # noqa: E501

        return self.api_client.call_api(
            '/v2.0.0/suppliers/{supplier_code}/inventory/{product_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InventoryLevelsResponseV200',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
