# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApparelSize(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'apparel_style': 'object',
        'label_size': 'object',
        'custom_size': 'object'
    }

    attribute_map = {
        'apparel_style': 'apparelStyle',
        'label_size': 'labelSize',
        'custom_size': 'customSize'
    }

    def __init__(self, apparel_style=None, label_size=None, custom_size=None):  # noqa: E501
        """ApparelSize - a model defined in Swagger"""  # noqa: E501
        self._apparel_style = None
        self._label_size = None
        self._custom_size = None
        self.discriminator = None
        self.apparel_style = apparel_style
        self.label_size = label_size
        self.custom_size = custom_size

    @property
    def apparel_style(self):
        """Gets the apparel_style of this ApparelSize.  # noqa: E501


        :return: The apparel_style of this ApparelSize.  # noqa: E501
        :rtype: object
        """
        return self._apparel_style

    @apparel_style.setter
    def apparel_style(self, apparel_style):
        """Sets the apparel_style of this ApparelSize.


        :param apparel_style: The apparel_style of this ApparelSize.  # noqa: E501
        :type: object
        """
        if apparel_style is None:
            raise ValueError("Invalid value for `apparel_style`, must not be `None`")  # noqa: E501

        self._apparel_style = apparel_style

    @property
    def label_size(self):
        """Gets the label_size of this ApparelSize.  # noqa: E501


        :return: The label_size of this ApparelSize.  # noqa: E501
        :rtype: object
        """
        return self._label_size

    @label_size.setter
    def label_size(self, label_size):
        """Sets the label_size of this ApparelSize.


        :param label_size: The label_size of this ApparelSize.  # noqa: E501
        :type: object
        """
        if label_size is None:
            raise ValueError("Invalid value for `label_size`, must not be `None`")  # noqa: E501

        self._label_size = label_size

    @property
    def custom_size(self):
        """Gets the custom_size of this ApparelSize.  # noqa: E501


        :return: The custom_size of this ApparelSize.  # noqa: E501
        :rtype: object
        """
        return self._custom_size

    @custom_size.setter
    def custom_size(self, custom_size):
        """Sets the custom_size of this ApparelSize.


        :param custom_size: The custom_size of this ApparelSize.  # noqa: E501
        :type: object
        """
        if custom_size is None:
            raise ValueError("Invalid value for `custom_size`, must not be `None`")  # noqa: E501

        self._custom_size = custom_size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApparelSize, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApparelSize):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
