# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AvailableChargesResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'available_charge_array': 'object',
        'error_message': 'object'
    }

    attribute_map = {
        'available_charge_array': 'AvailableChargeArray',
        'error_message': 'ErrorMessage'
    }

    def __init__(self, available_charge_array=None, error_message=None):  # noqa: E501
        """AvailableChargesResponse - a model defined in Swagger"""  # noqa: E501
        self._available_charge_array = None
        self._error_message = None
        self.discriminator = None
        self.available_charge_array = available_charge_array
        if error_message is not None:
            self.error_message = error_message

    @property
    def available_charge_array(self):
        """Gets the available_charge_array of this AvailableChargesResponse.  # noqa: E501


        :return: The available_charge_array of this AvailableChargesResponse.  # noqa: E501
        :rtype: object
        """
        return self._available_charge_array

    @available_charge_array.setter
    def available_charge_array(self, available_charge_array):
        """Sets the available_charge_array of this AvailableChargesResponse.


        :param available_charge_array: The available_charge_array of this AvailableChargesResponse.  # noqa: E501
        :type: object
        """
        if available_charge_array is None:
            raise ValueError("Invalid value for `available_charge_array`, must not be `None`")  # noqa: E501

        self._available_charge_array = available_charge_array

    @property
    def error_message(self):
        """Gets the error_message of this AvailableChargesResponse.  # noqa: E501


        :return: The error_message of this AvailableChargesResponse.  # noqa: E501
        :rtype: object
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this AvailableChargesResponse.


        :param error_message: The error_message of this AvailableChargesResponse.  # noqa: E501
        :type: object
        """

        self._error_message = error_message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AvailableChargesResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AvailableChargesResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
