# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClassType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'class_type_id': 'object',
        'class_type_name': 'object'
    }

    attribute_map = {
        'class_type_id': 'classTypeId',
        'class_type_name': 'classTypeName'
    }

    def __init__(self, class_type_id=None, class_type_name=None):  # noqa: E501
        """ClassType - a model defined in Swagger"""  # noqa: E501
        self._class_type_id = None
        self._class_type_name = None
        self.discriminator = None
        self.class_type_id = class_type_id
        self.class_type_name = class_type_name

    @property
    def class_type_id(self):
        """Gets the class_type_id of this ClassType.  # noqa: E501


        :return: The class_type_id of this ClassType.  # noqa: E501
        :rtype: object
        """
        return self._class_type_id

    @class_type_id.setter
    def class_type_id(self, class_type_id):
        """Sets the class_type_id of this ClassType.


        :param class_type_id: The class_type_id of this ClassType.  # noqa: E501
        :type: object
        """
        if class_type_id is None:
            raise ValueError("Invalid value for `class_type_id`, must not be `None`")  # noqa: E501

        self._class_type_id = class_type_id

    @property
    def class_type_name(self):
        """Gets the class_type_name of this ClassType.  # noqa: E501


        :return: The class_type_name of this ClassType.  # noqa: E501
        :rtype: object
        """
        return self._class_type_name

    @class_type_name.setter
    def class_type_name(self, class_type_name):
        """Sets the class_type_name of this ClassType.


        :param class_type_name: The class_type_name of this ClassType.  # noqa: E501
        :type: object
        """
        if class_type_name is None:
            raise ValueError("Invalid value for `class_type_name`, must not be `None`")  # noqa: E501

        self._class_type_name = class_type_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClassType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClassType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
