# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Layers(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'color_system': 'ColorSystem',
        'layer_or_stop_array': 'LayerOrStopArray'
    }

    attribute_map = {
        'color_system': 'colorSystem',
        'layer_or_stop_array': 'LayerOrStopArray'
    }

    def __init__(self, color_system=None, layer_or_stop_array=None):  # noqa: E501
        """Layers - a model defined in Swagger"""  # noqa: E501
        self._color_system = None
        self._layer_or_stop_array = None
        self.discriminator = None
        self.color_system = color_system
        self.layer_or_stop_array = layer_or_stop_array

    @property
    def color_system(self):
        """Gets the color_system of this Layers.  # noqa: E501


        :return: The color_system of this Layers.  # noqa: E501
        :rtype: ColorSystem
        """
        return self._color_system

    @color_system.setter
    def color_system(self, color_system):
        """Sets the color_system of this Layers.


        :param color_system: The color_system of this Layers.  # noqa: E501
        :type: ColorSystem
        """
        if color_system is None:
            raise ValueError("Invalid value for `color_system`, must not be `None`")  # noqa: E501

        self._color_system = color_system

    @property
    def layer_or_stop_array(self):
        """Gets the layer_or_stop_array of this Layers.  # noqa: E501


        :return: The layer_or_stop_array of this Layers.  # noqa: E501
        :rtype: LayerOrStopArray
        """
        return self._layer_or_stop_array

    @layer_or_stop_array.setter
    def layer_or_stop_array(self, layer_or_stop_array):
        """Sets the layer_or_stop_array of this Layers.


        :param layer_or_stop_array: The layer_or_stop_array of this Layers.  # noqa: E501
        :type: LayerOrStopArray
        """
        if layer_or_stop_array is None:
            raise ValueError("Invalid value for `layer_or_stop_array`, must not be `None`")  # noqa: E501

        self._layer_or_stop_array = layer_or_stop_array

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Layers, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Layers):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
