# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LocationInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'location_link_id': 'object',
        'location_id': 'object',
        'location_name': 'object',
        'decoration_array': 'DecorationArrayInput'
    }

    attribute_map = {
        'location_link_id': 'locationLinkId',
        'location_id': 'locationId',
        'location_name': 'locationName',
        'decoration_array': 'DecorationArray'
    }

    def __init__(self, location_link_id=None, location_id=None, location_name=None, decoration_array=None):  # noqa: E501
        """LocationInput - a model defined in Swagger"""  # noqa: E501
        self._location_link_id = None
        self._location_id = None
        self._location_name = None
        self._decoration_array = None
        self.discriminator = None
        self.location_link_id = location_link_id
        self.location_id = location_id
        self.location_name = location_name
        self.decoration_array = decoration_array

    @property
    def location_link_id(self):
        """Gets the location_link_id of this LocationInput.  # noqa: E501

        An identifier to be used within the Part Array to link configured locations to a part.  Due to different colors and sizes, identical locations may need to be decorated differently  # noqa: E501

        :return: The location_link_id of this LocationInput.  # noqa: E501
        :rtype: object
        """
        return self._location_link_id

    @location_link_id.setter
    def location_link_id(self, location_link_id):
        """Sets the location_link_id of this LocationInput.

        An identifier to be used within the Part Array to link configured locations to a part.  Due to different colors and sizes, identical locations may need to be decorated differently  # noqa: E501

        :param location_link_id: The location_link_id of this LocationInput.  # noqa: E501
        :type: object
        """
        if location_link_id is None:
            raise ValueError("Invalid value for `location_link_id`, must not be `None`")  # noqa: E501

        self._location_link_id = location_link_id

    @property
    def location_id(self):
        """Gets the location_id of this LocationInput.  # noqa: E501

        The locationId from the supplier’s PromoStandards Product Pricing and Configuration service  # noqa: E501

        :return: The location_id of this LocationInput.  # noqa: E501
        :rtype: object
        """
        return self._location_id

    @location_id.setter
    def location_id(self, location_id):
        """Sets the location_id of this LocationInput.

        The locationId from the supplier’s PromoStandards Product Pricing and Configuration service  # noqa: E501

        :param location_id: The location_id of this LocationInput.  # noqa: E501
        :type: object
        """
        if location_id is None:
            raise ValueError("Invalid value for `location_id`, must not be `None`")  # noqa: E501

        self._location_id = location_id

    @property
    def location_name(self):
        """Gets the location_name of this LocationInput.  # noqa: E501

        The locationName from the supplier’s PromoStandards Product Pricing and Configuration service  # noqa: E501

        :return: The location_name of this LocationInput.  # noqa: E501
        :rtype: object
        """
        return self._location_name

    @location_name.setter
    def location_name(self, location_name):
        """Sets the location_name of this LocationInput.

        The locationName from the supplier’s PromoStandards Product Pricing and Configuration service  # noqa: E501

        :param location_name: The location_name of this LocationInput.  # noqa: E501
        :type: object
        """
        if location_name is None:
            raise ValueError("Invalid value for `location_name`, must not be `None`")  # noqa: E501

        self._location_name = location_name

    @property
    def decoration_array(self):
        """Gets the decoration_array of this LocationInput.  # noqa: E501


        :return: The decoration_array of this LocationInput.  # noqa: E501
        :rtype: DecorationArrayInput
        """
        return self._decoration_array

    @decoration_array.setter
    def decoration_array(self, decoration_array):
        """Sets the decoration_array of this LocationInput.


        :param decoration_array: The decoration_array of this LocationInput.  # noqa: E501
        :type: DecorationArrayInput
        """
        if decoration_array is None:
            raise ValueError("Invalid value for `decoration_array`, must not be `None`")  # noqa: E501

        self._decoration_array = decoration_array

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LocationInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LocationInput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
