# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProductPackage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'default': 'object',
        'package_type': 'object',
        'description': 'object',
        'quantity': 'object',
        'dimension_uom': 'DimensionUoMOutput',
        'depth': 'object',
        'height': 'object',
        'width': 'object',
        'weight_uom': 'WeightUoM',
        'weight': 'object'
    }

    attribute_map = {
        'default': 'default',
        'package_type': 'packageType',
        'description': 'description',
        'quantity': 'quantity',
        'dimension_uom': 'dimensionUom',
        'depth': 'depth',
        'height': 'height',
        'width': 'width',
        'weight_uom': 'weightUom',
        'weight': 'weight'
    }

    def __init__(self, default=None, package_type=None, description=None, quantity=None, dimension_uom=None, depth=None, height=None, width=None, weight_uom=None, weight=None):  # noqa: E501
        """ProductPackage - a model defined in Swagger"""  # noqa: E501
        self._default = None
        self._package_type = None
        self._description = None
        self._quantity = None
        self._dimension_uom = None
        self._depth = None
        self._height = None
        self._width = None
        self._weight_uom = None
        self._weight = None
        self.discriminator = None
        self.default = default
        self.package_type = package_type
        self.description = description
        self.quantity = quantity
        self.dimension_uom = dimension_uom
        self.depth = depth
        self.height = height
        self.width = width
        self.weight_uom = weight_uom
        self.weight = weight

    @property
    def default(self):
        """Gets the default of this ProductPackage.  # noqa: E501


        :return: The default of this ProductPackage.  # noqa: E501
        :rtype: object
        """
        return self._default

    @default.setter
    def default(self, default):
        """Sets the default of this ProductPackage.


        :param default: The default of this ProductPackage.  # noqa: E501
        :type: object
        """
        if default is None:
            raise ValueError("Invalid value for `default`, must not be `None`")  # noqa: E501

        self._default = default

    @property
    def package_type(self):
        """Gets the package_type of this ProductPackage.  # noqa: E501


        :return: The package_type of this ProductPackage.  # noqa: E501
        :rtype: object
        """
        return self._package_type

    @package_type.setter
    def package_type(self, package_type):
        """Sets the package_type of this ProductPackage.


        :param package_type: The package_type of this ProductPackage.  # noqa: E501
        :type: object
        """
        if package_type is None:
            raise ValueError("Invalid value for `package_type`, must not be `None`")  # noqa: E501

        self._package_type = package_type

    @property
    def description(self):
        """Gets the description of this ProductPackage.  # noqa: E501


        :return: The description of this ProductPackage.  # noqa: E501
        :rtype: object
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ProductPackage.


        :param description: The description of this ProductPackage.  # noqa: E501
        :type: object
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def quantity(self):
        """Gets the quantity of this ProductPackage.  # noqa: E501


        :return: The quantity of this ProductPackage.  # noqa: E501
        :rtype: object
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this ProductPackage.


        :param quantity: The quantity of this ProductPackage.  # noqa: E501
        :type: object
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity

    @property
    def dimension_uom(self):
        """Gets the dimension_uom of this ProductPackage.  # noqa: E501


        :return: The dimension_uom of this ProductPackage.  # noqa: E501
        :rtype: DimensionUoMOutput
        """
        return self._dimension_uom

    @dimension_uom.setter
    def dimension_uom(self, dimension_uom):
        """Sets the dimension_uom of this ProductPackage.


        :param dimension_uom: The dimension_uom of this ProductPackage.  # noqa: E501
        :type: DimensionUoMOutput
        """
        if dimension_uom is None:
            raise ValueError("Invalid value for `dimension_uom`, must not be `None`")  # noqa: E501

        self._dimension_uom = dimension_uom

    @property
    def depth(self):
        """Gets the depth of this ProductPackage.  # noqa: E501


        :return: The depth of this ProductPackage.  # noqa: E501
        :rtype: object
        """
        return self._depth

    @depth.setter
    def depth(self, depth):
        """Sets the depth of this ProductPackage.


        :param depth: The depth of this ProductPackage.  # noqa: E501
        :type: object
        """
        if depth is None:
            raise ValueError("Invalid value for `depth`, must not be `None`")  # noqa: E501

        self._depth = depth

    @property
    def height(self):
        """Gets the height of this ProductPackage.  # noqa: E501


        :return: The height of this ProductPackage.  # noqa: E501
        :rtype: object
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this ProductPackage.


        :param height: The height of this ProductPackage.  # noqa: E501
        :type: object
        """
        if height is None:
            raise ValueError("Invalid value for `height`, must not be `None`")  # noqa: E501

        self._height = height

    @property
    def width(self):
        """Gets the width of this ProductPackage.  # noqa: E501


        :return: The width of this ProductPackage.  # noqa: E501
        :rtype: object
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this ProductPackage.


        :param width: The width of this ProductPackage.  # noqa: E501
        :type: object
        """
        if width is None:
            raise ValueError("Invalid value for `width`, must not be `None`")  # noqa: E501

        self._width = width

    @property
    def weight_uom(self):
        """Gets the weight_uom of this ProductPackage.  # noqa: E501


        :return: The weight_uom of this ProductPackage.  # noqa: E501
        :rtype: WeightUoM
        """
        return self._weight_uom

    @weight_uom.setter
    def weight_uom(self, weight_uom):
        """Sets the weight_uom of this ProductPackage.


        :param weight_uom: The weight_uom of this ProductPackage.  # noqa: E501
        :type: WeightUoM
        """
        if weight_uom is None:
            raise ValueError("Invalid value for `weight_uom`, must not be `None`")  # noqa: E501

        self._weight_uom = weight_uom

    @property
    def weight(self):
        """Gets the weight of this ProductPackage.  # noqa: E501


        :return: The weight of this ProductPackage.  # noqa: E501
        :rtype: object
        """
        return self._weight

    @weight.setter
    def weight(self, weight):
        """Sets the weight of this ProductPackage.


        :param weight: The weight of this ProductPackage.  # noqa: E501
        :type: object
        """
        if weight is None:
            raise ValueError("Invalid value for `weight`, must not be `None`")  # noqa: E501

        self._weight = weight

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductPackage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductPackage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
