# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PsDomainModelOrderStatusV200OrderStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'purchase_order_number': 'object',
        'order_status_detail_array': 'PsDomainModelOrderStatusV200OrderStatusDetailArray',
        'audit_url': 'object'
    }

    attribute_map = {
        'purchase_order_number': 'purchaseOrderNumber',
        'order_status_detail_array': 'OrderStatusDetailArray',
        'audit_url': 'auditURL'
    }

    def __init__(self, purchase_order_number=None, order_status_detail_array=None, audit_url=None):  # noqa: E501
        """PsDomainModelOrderStatusV200OrderStatus - a model defined in Swagger"""  # noqa: E501
        self._purchase_order_number = None
        self._order_status_detail_array = None
        self._audit_url = None
        self.discriminator = None
        self.purchase_order_number = purchase_order_number
        self.order_status_detail_array = order_status_detail_array
        if audit_url is not None:
            self.audit_url = audit_url

    @property
    def purchase_order_number(self):
        """Gets the purchase_order_number of this PsDomainModelOrderStatusV200OrderStatus.  # noqa: E501


        :return: The purchase_order_number of this PsDomainModelOrderStatusV200OrderStatus.  # noqa: E501
        :rtype: object
        """
        return self._purchase_order_number

    @purchase_order_number.setter
    def purchase_order_number(self, purchase_order_number):
        """Sets the purchase_order_number of this PsDomainModelOrderStatusV200OrderStatus.


        :param purchase_order_number: The purchase_order_number of this PsDomainModelOrderStatusV200OrderStatus.  # noqa: E501
        :type: object
        """
        if purchase_order_number is None:
            raise ValueError("Invalid value for `purchase_order_number`, must not be `None`")  # noqa: E501

        self._purchase_order_number = purchase_order_number

    @property
    def order_status_detail_array(self):
        """Gets the order_status_detail_array of this PsDomainModelOrderStatusV200OrderStatus.  # noqa: E501


        :return: The order_status_detail_array of this PsDomainModelOrderStatusV200OrderStatus.  # noqa: E501
        :rtype: PsDomainModelOrderStatusV200OrderStatusDetailArray
        """
        return self._order_status_detail_array

    @order_status_detail_array.setter
    def order_status_detail_array(self, order_status_detail_array):
        """Sets the order_status_detail_array of this PsDomainModelOrderStatusV200OrderStatus.


        :param order_status_detail_array: The order_status_detail_array of this PsDomainModelOrderStatusV200OrderStatus.  # noqa: E501
        :type: PsDomainModelOrderStatusV200OrderStatusDetailArray
        """
        if order_status_detail_array is None:
            raise ValueError("Invalid value for `order_status_detail_array`, must not be `None`")  # noqa: E501

        self._order_status_detail_array = order_status_detail_array

    @property
    def audit_url(self):
        """Gets the audit_url of this PsDomainModelOrderStatusV200OrderStatus.  # noqa: E501


        :return: The audit_url of this PsDomainModelOrderStatusV200OrderStatus.  # noqa: E501
        :rtype: object
        """
        return self._audit_url

    @audit_url.setter
    def audit_url(self, audit_url):
        """Sets the audit_url of this PsDomainModelOrderStatusV200OrderStatus.


        :param audit_url: The audit_url of this PsDomainModelOrderStatusV200OrderStatus.  # noqa: E501
        :type: object
        """

        self._audit_url = audit_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PsDomainModelOrderStatusV200OrderStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PsDomainModelOrderStatusV200OrderStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
