# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RealFilterValues(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'product_id': 'object',
        'part_id': 'object',
        'label_size_array': 'object',
        'part_color_array': 'object',
        'selection_array': 'object'
    }

    attribute_map = {
        'product_id': 'productId',
        'part_id': 'partId',
        'label_size_array': 'LabelSizeArray',
        'part_color_array': 'PartColorArray',
        'selection_array': 'SelectionArray'
    }

    def __init__(self, product_id=None, part_id=None, label_size_array=None, part_color_array=None, selection_array=None):  # noqa: E501
        """RealFilterValues - a model defined in Swagger"""  # noqa: E501
        self._product_id = None
        self._part_id = None
        self._label_size_array = None
        self._part_color_array = None
        self._selection_array = None
        self.discriminator = None
        if product_id is not None:
            self.product_id = product_id
        if part_id is not None:
            self.part_id = part_id
        self.label_size_array = label_size_array
        self.part_color_array = part_color_array
        self.selection_array = selection_array

    @property
    def product_id(self):
        """Gets the product_id of this RealFilterValues.  # noqa: E501


        :return: The product_id of this RealFilterValues.  # noqa: E501
        :rtype: object
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id):
        """Sets the product_id of this RealFilterValues.


        :param product_id: The product_id of this RealFilterValues.  # noqa: E501
        :type: object
        """

        self._product_id = product_id

    @property
    def part_id(self):
        """Gets the part_id of this RealFilterValues.  # noqa: E501


        :return: The part_id of this RealFilterValues.  # noqa: E501
        :rtype: object
        """
        return self._part_id

    @part_id.setter
    def part_id(self, part_id):
        """Sets the part_id of this RealFilterValues.


        :param part_id: The part_id of this RealFilterValues.  # noqa: E501
        :type: object
        """

        self._part_id = part_id

    @property
    def label_size_array(self):
        """Gets the label_size_array of this RealFilterValues.  # noqa: E501


        :return: The label_size_array of this RealFilterValues.  # noqa: E501
        :rtype: object
        """
        return self._label_size_array

    @label_size_array.setter
    def label_size_array(self, label_size_array):
        """Sets the label_size_array of this RealFilterValues.


        :param label_size_array: The label_size_array of this RealFilterValues.  # noqa: E501
        :type: object
        """
        if label_size_array is None:
            raise ValueError("Invalid value for `label_size_array`, must not be `None`")  # noqa: E501

        self._label_size_array = label_size_array

    @property
    def part_color_array(self):
        """Gets the part_color_array of this RealFilterValues.  # noqa: E501


        :return: The part_color_array of this RealFilterValues.  # noqa: E501
        :rtype: object
        """
        return self._part_color_array

    @part_color_array.setter
    def part_color_array(self, part_color_array):
        """Sets the part_color_array of this RealFilterValues.


        :param part_color_array: The part_color_array of this RealFilterValues.  # noqa: E501
        :type: object
        """
        if part_color_array is None:
            raise ValueError("Invalid value for `part_color_array`, must not be `None`")  # noqa: E501

        self._part_color_array = part_color_array

    @property
    def selection_array(self):
        """Gets the selection_array of this RealFilterValues.  # noqa: E501


        :return: The selection_array of this RealFilterValues.  # noqa: E501
        :rtype: object
        """
        return self._selection_array

    @selection_array.setter
    def selection_array(self, selection_array):
        """Sets the selection_array of this RealFilterValues.


        :param selection_array: The selection_array of this RealFilterValues.  # noqa: E501
        :type: object
        """
        if selection_array is None:
            raise ValueError("Invalid value for `selection_array`, must not be `None`")  # noqa: E501

        self._selection_array = selection_array

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RealFilterValues, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RealFilterValues):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
