# coding: utf-8

"""
    PS RESTful Service API

    A proxy service for PromoStandards SOAP to a REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RelatedProduct(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'relation_type': 'object',
        'product_id': 'object',
        'part_id': 'object'
    }

    attribute_map = {
        'relation_type': 'relationType',
        'product_id': 'productId',
        'part_id': 'partId'
    }

    def __init__(self, relation_type=None, product_id=None, part_id=None):  # noqa: E501
        """RelatedProduct - a model defined in Swagger"""  # noqa: E501
        self._relation_type = None
        self._product_id = None
        self._part_id = None
        self.discriminator = None
        self.relation_type = relation_type
        self.product_id = product_id
        self.part_id = part_id

    @property
    def relation_type(self):
        """Gets the relation_type of this RelatedProduct.  # noqa: E501


        :return: The relation_type of this RelatedProduct.  # noqa: E501
        :rtype: object
        """
        return self._relation_type

    @relation_type.setter
    def relation_type(self, relation_type):
        """Sets the relation_type of this RelatedProduct.


        :param relation_type: The relation_type of this RelatedProduct.  # noqa: E501
        :type: object
        """
        if relation_type is None:
            raise ValueError("Invalid value for `relation_type`, must not be `None`")  # noqa: E501

        self._relation_type = relation_type

    @property
    def product_id(self):
        """Gets the product_id of this RelatedProduct.  # noqa: E501


        :return: The product_id of this RelatedProduct.  # noqa: E501
        :rtype: object
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id):
        """Sets the product_id of this RelatedProduct.


        :param product_id: The product_id of this RelatedProduct.  # noqa: E501
        :type: object
        """
        if product_id is None:
            raise ValueError("Invalid value for `product_id`, must not be `None`")  # noqa: E501

        self._product_id = product_id

    @property
    def part_id(self):
        """Gets the part_id of this RelatedProduct.  # noqa: E501


        :return: The part_id of this RelatedProduct.  # noqa: E501
        :rtype: object
        """
        return self._part_id

    @part_id.setter
    def part_id(self, part_id):
        """Sets the part_id of this RelatedProduct.


        :param part_id: The part_id of this RelatedProduct.  # noqa: E501
        :type: object
        """
        if part_id is None:
            raise ValueError("Invalid value for `part_id`, must not be `None`")  # noqa: E501

        self._part_id = part_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RelatedProduct, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RelatedProduct):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
